// angular/angular-components/src/components/atoms/label.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'label-component',
  template: `
    <div>
      <div [ngStyle]="labelStyles" [ngClass]="labelClasses" [attr.id]="labelId">
        {{ text }}
      </div>
    </div>
  `,
  styles: [
    `
      .label {
        font-family: 'Open Sans', sans-serif;
      }
      .ellipsed {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
    `,
  ],
})
export class LabelComponent {
  @Input() text: string = 'Default Title';
  @Input() size: string = 'medium';
  @Input() color: string = '';
  @Input() bold: boolean = false;
  @Input() ellipsed: boolean = false;

  labelSizes = {
    small: '0.625rem',
    medium: '0.875rem',
    large: '4rem',
  };

  get labelStyles() {
    return {
      'font-weight': this.bold ? 'bold' : '',
      'font-family': 'Open Sans, sans-serif',
      'font-size':
        this.labelSizes[(this?.size as 'small') || 'medium' || 'large'] ||
        this.labelSizes.medium,
      color: this.color || '#232323',
    };
  }

  get labelClasses() {
    return {
      label: true,
      ellipsed: this.ellipsed,
    };
  }

  get labelId() {
    return 'label';
  }
}

// vue/vue-components/src/components/atoms/Label.vue
<template>
  <div>
    <div
      :style="{
        fontWeight: bold ? 'bold' : '',
        fontFamily: 'Open Sans, sans-serif',
        fontSize: labelSizes[size] || labelSizes.medium,
        color: color || '#232323',
      }"
      :class="{ label: true, ellipsed: ellipsed }"
      :id="labelId"
    >
      {{ text }}
    </div>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      default: "Default Title",
    },
    size: {
      type: String,
      default: "medium",
    },
    color: {
      type: String,
      default: "",
    },
    bold: {
      type: Boolean,
      default: false,
    },
    ellipsed: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      labelSizes: {
        small: "0.625rem",
        medium: "0.875rem",
        large: "4rem",
      },
    };
  },
  computed: {
    labelId() {
      return "label";
    },
  },
};
</script>

<style scoped>
.label {
  font-family: "Open Sans", sans-serif;
}

.ellipsed {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
