// svelte/svelte-components/src/components/atoms/LabelComponent.svelte
<script>
    export let text = "Default Title";
    export let size = "medium";
    export let color = "";
    export let bold = false;
    export let ellipsed = false;
  
    const labelSizes = {
      small: "0.625rem",
      medium: "0.875rem",
      large: "4rem",
    };
  
    function getFontSize() {
      // @ts-ignore
      return labelSizes[size] || labelSizes.medium;
    }
  
    function getFontWeight() {
      return bold ? "bold" : "normal";
    }
  
    function getLabelStyle() {
      return `font-weight: ${getFontWeight()}; font-family: 'Open Sans', sans-serif; font-size: ${getFontSize()}; color: ${color || "#232323"};`;
    }
  
    let labelClass = ellipsed ? "label ellipsed" : "label";
  
  </script>
  
  <div>
    <div style={getLabelStyle()} class={labelClass} id="label">
      {text}
    </div>
  </div>

// next/next-components/src/components/atoms/label.jsx
import React from "react";

const labelSizes = {
  small: "0.625rem",
  medium: "0.875rem",
  large: "4rem",
};

const LabelComponent = ({
  text = "Default Title",
  size = "medium",
  color = "",
  bold = false,
  ellipsed = false,
}) => {
  return (
    <div>
      <div
        style={{
          fontWeight: `${bold ? "bold" : ""}`,
          fontFamily: "'Open Sans', sans-serif",
          fontSize: `${labelSizes[size] || labelSizes.medium}`,
          color: `${color || "#232323"}`,
        }}
        className={`label ${ellipsed && "ellipsed"}`}
        id="label"
      >
        {text}
      </div>
    </div>
  );
};

export default LabelComponent;
