// svelte/svelte-components/src/components/molecules/SearchInputComponent.svelte
<script>
  // @ts-nocheck

  import { onMount } from "svelte";

  export let value = "";
  export let onChange = null;
  export let inputValue = value;

  const inputRef = undefined;

  const handleInput = (event) => {
    const newValue = event.target.value;
    inputValue = newValue;

    if (onChange) {
      onChange(newValue);
    }
  };

  onMount(() => {
    if (inputRef) {
      inputRef.value = value;
    }
  });
</script>

<div class="searchInputContainer">
  <img
    src="/icons/search.svg"
    alt="Search icon"
    width="18px"
    height="17px"
    style="margin-left: .5rem"
  />
  <input
    type="text"
    class="searchInput"
    placeholder="Search a book by its name or author"
    bind:value={inputValue}
    on:input={handleInput}
  />
</div>

// vue/vue-components/src/components/molecules/SearchInput.vue
<template>
  <div class="searchInputContainer">
    <img
      src="/icons/search.svg"
      alt="Search icon"
      style="margin-left: 0.5rem; width: 18px; height: 17px;"
    />
    <input
      type="text"
      class="searchInput"
      placeholder="Search a book by its name or author"
      ref="inputRef"
      :value="inputValue"
      @input="handleInput"
    />
  </div>
</template>

<script>
export default {
  props: {
    value: String,
    onChange: Function,
  },
  data() {
    return {
      inputValue: this.value || "",
    };
  },
  methods: {
    handleInput(event) {
      const newValue = event.target.value;
      this.inputValue = newValue;

      // Call the onChange function if it's provided
      if (this.onChange) {
        this.onChange(newValue);
      }
    },
  },
};
</script>

<style scoped>
/* Add your CSS styles here */
</style>
