// angular/angular-components/src/app/app.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  @ViewChild('bookItemComponent') bookItemComponent!: ElementRef;

  recentBooks: any[] = [];
  searchedBooks: any[] = [];
  sidebarBookInfo: any = null;

  private searchInputTimer: any;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    // Call the fetchData function when the page loads
    this.fetchData();
    this.fetchSearchedData('programming');
  }

  getBookDetails(bookId: string) {
    if (this.sidebarBookInfo && this.sidebarBookInfo.id === bookId) {
      // If the same book is clicked again, close the sidebar
      this.sidebarBookInfo = null;
    } else {
      // Fetch book details from the API
      this.http
        .get(`https://www.dbooks.org/api/book/${bookId}`)
        .subscribe((data: any) => {
          this.sidebarBookInfo = data;
        });
    }
  }

  fetchSearchedData(query: any) {
    if (query) {
      // Fetch searched data from the API
      this.http
        .get(`https://www.dbooks.org/api/search/${query}`)
        .subscribe((data: any) => {
          if (data.status === 'ok' && data.books && data.books.length > 0) {
            this.searchedBooks = data.books;
          } else {
            this.searchedBooks = [];
          }
        });
    } else {
      this.searchedBooks = [];
    }
  }

  fetchData() {
    // Fetch recent books from the API
    this.http
      .get('https://www.dbooks.org/api/recent')
      .subscribe((data: any) => {
        if (data.status === 'ok' && data.books && data.books.length > 0) {
          this.recentBooks = data.books.slice(0, 5);
        }
      });
  }

  handleSearchInputChange(event: any) {
    if (this.searchInputTimer) {
      clearTimeout(this.searchInputTimer);
    }

    // Set a new timer to fetch data after a delay
    this.searchInputTimer = setTimeout(() => {
      this.fetchSearchedData(event.target.value);
    }, 1000); // 1000 milliseconds (1 second)
  }
}

<div style="display: flex; justify-content: center">
  <div style="padding: 50px; max-width: 57.375rem; margin-right: 22.625rem">
    <div style="display: flex; flex-direction: column; gap: 10px">
      <div style="line-height: 25px">
        <title-component text="Most recent books"></title-component>
        <label-component
          text="Here you can visualize the most recent added books."
        ></label-component>
      </div>
      <div
        class="books-container"
        style="
          display: flex;
          flex-direction: row;
          flex-wrap: wrap;
          justify-content: space-between;
          row-gap: 20px;
          margin-bottom: 40px;
        "
      >
        <book-item-component
          *ngFor="let book of recentBooks"
          [title]="book.title"
          [label]="book.authors"
          [path]="book.image"
          (click)="getBookDetails(book.id)"
        ></book-item-component>
      </div>
    </div>
    <div
      style="
        display: flex;
        align-items: end;
        justify-content: space between;
        margin-bottom: 20px;
      "
    >
      <div>
        <title-component text="Search for books"></title-component>
        <label-component
          text="Here you can search your book of interest by the name of the author or book title."
        ></label-component>
      </div>
      <div>
        <search-input-component
        (input)="handleSearchInputChange($event)"
        ></search-input-component>
      </div>
    </div>
    <div
      class="searched-books-container"
      style="
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
        row-gap: 20px;
        margin-bottom: 40px;
      "
    >
      <div *ngFor="let book of searchedBooks; let i = index">
        <book-item-component
          [title]="book.title"
          [label]="book.authors"
          [path]="book.image"
          (click)="getBookDetails(book.id)"
        ></book-item-component>
      </div>
    </div>
  </div>
</div>
<sidebar-component [bookInfo]="sidebarBookInfo"></sidebar-component>
<router-outlet></router-outlet>

// next/next-web-components-lib/src/app/page.js
"use client";
import Script from "next/script";
import { useEffect, useState } from "react";

const Home = () => {
  const [currentBookId, setCurrentBookId] = useState("");
  const [searchedData, setSearchedData] = useState([]);
  const [recentBooks, setRecentBooks] = useState([]);

  useEffect(() => {
    fetchData();
    fetchSearchedData("programming");
  }, []);


  const getBookDetails = (bookId) => {
    if (currentBookId !== bookId) {
      fetch(`https://www.dbooks.org/api/book/${bookId}`)
        .then((response) => {
          if (!response.ok) {
            throw new Error("Network response was not ok");
          }
          return response.json();
        })
        .then((data) => {
          const sidebar = document.querySelector("sidebar-component");
          // Update state or component as needed with book details
          setCurrentBookId(data.id);
          sidebar.bookInfo = data;
        });
    } else {
      const sidebar = document.querySelector("sidebar-component");
      sidebar.bookInfo = null;
      // Clear book details or update component as needed
      setCurrentBookId("");
    }
  };

  const fetchSearchedData = (query) => {
    if (query) {
      fetch(`https://www.dbooks.org/api/search/${query}`)
        .then((response) => {
          if (!response.ok) {
            throw new Error("Network response was not ok");
          }
          return response.json();
        })
        .then((data) => {
          if (data.status === "ok" && data.books && data.books.length > 0) {
            setSearchedData(data.books);
          } else {
            setSearchedData([]);
          }
        });
    } else {
      setSearchedData([]);
    }
  };

  const fetchData = () => {
    fetch("https://www.dbooks.org/api/recent")
      .then((response) => {
        if (!response.ok) {
          throw new Error("Network response was not ok");
        }
        return response.json();
      })
      .then((data) => {
        if (data.status === "ok" && data.books && data.books.length > 0) {
          setRecentBooks(data.books.slice(0, 5));
        }
      });
  };

  let searchInputTimer;

  function handleSearchInputChange(event) {
    // Clear the previous timer, if it exists
    if (searchInputTimer) {
      clearTimeout(searchInputTimer);
    }

    // Set a new timer to log the value after 3 seconds with no changes
    searchInputTimer = setTimeout(() => {
      fetchSearchedData(event)
    }, 1000); // 3000 milliseconds (3 seconds)
  }

  useEffect(() => {
    const searchInput = document.querySelector("search-input-component");
        
    searchInput.onChange = handleSearchInputChange;
  },[])

  return (
    <div>
      <Script src="/build/bundle.js" type="module"/>
      <style jsx>{`
        .books-container {
          display: flex;
          flex-direction: row;
          flex-wrap: wrap;
          justify-content: space-between;
          row-gap: 20px;
          margin-bottom: 40px;
        }
        .container {
          padding: 50px;
          max-width: 57.375rem;
          margin-right: 22.625rem;
        }
        .search-container {
          display: flex;
          align-items: end;
          justify-content: space-between;
          margin-bottom: 20px;
        }
      `}</style>
      <div className="container">
        <div>
          <title-component text="Most recent books" />
          <label-component text="Here you can visualize the most recent added books." />
        </div>
        <div className="books-container">
          {recentBooks.map((book) => (
            <book-item-component
              key={book.id}
              title={book.title}
              label={book.authors}
              path={book.image}
              onClick={() => getBookDetails(book.id)}
            />
          ))}
        </div>
        <div className="search-container">
          <div>
            <title-component text="Search for books" />
            <label-component text="Here you can search your book of interest by the name of the author or book title." />
          </div>
          <div>
            <search-input-component value="initial value"/>
          </div>
        </div>
        <div className="books-container">
          {searchedData.map((book) => (
            <book-item-component
              key={book.id}
              title={book.title}
              label={book.authors}
              path={book.image}
              onClick={() => getBookDetails(book.id)}
            />
          ))}
        </div>
      </div>
      <div>
        <sidebar-component />
      </div>
    </div>
  );
};

export default Home;
