// vue/vue-components/src/components/molecules/Sidebar.vue
<template>
  <div class="sidebar">
    <LogoComponent :selected="!!bookInfo" />
    <TitleComponent text="Book Shelf" size="large" color="white" />
    <div
      v-if="bookInfo"
      style="
        width: 15rem;
        height: 13rem;
        text-align: left;
        display: flex;
        flex-direction: column;
        gap: 1rem;
        overflow-y: scroll;
      "
    >
      <div class="bookDescription">
        <LabelComponent
          text="Title:"
          size="medium"
          color="white"
          :bold="true"
        />
        <LabelComponent :text="bookInfo.title" size="medium" color="white" />
      </div>
      <div class="bookDescription">
        <LabelComponent
          text="Subtitle:"
          size="medium"
          color="white"
          :bold="true"
        />
        <LabelComponent :text="bookInfo.subtitle" size="medium" color="white" />
      </div>
      <div class="bookDescription">
        <LabelComponent
          text="Authors:"
          size="medium"
          color="white"
          :bold="true"
        />
        <LabelComponent :text="bookInfo.authors" size="medium" color="white" />
      </div>
      <div class="bookDescription">
        <LabelComponent
          text="Description:"
          size="medium"
          color="white"
          :bold="true"
        />
        <LabelComponent
          :text="bookInfo.description"
          size="medium"
          color="white"
        />
      </div>
      <div class="bookDescription">
        <LabelComponent text="Year:" size="medium" color="white" :bold="true" />
        <LabelComponent :text="bookInfo.year" size="medium" color="white" />
      </div>
      <div>
        <LabelComponent
          text="Pages:"
          size="medium"
          color="white"
          :bold="true"
        />
        <LabelComponent :text="bookInfo.pages" size="medium" color="white" />
      </div>
    </div>
    <a v-if="bookInfo" class="button" :href="bookInfo.download" target="_blank"
      >Download</a
    >
    <div v-else>
      <LabelComponent
        text="(Select a book to see its specifications here!)"
        size="small"
        color="white"
      />
    </div>
  </div>
</template>

<script>
import LogoComponent from "../atoms/Logo.vue";
import TitleComponent from "../atoms/title.vue";
import LabelComponent from "../atoms/Label.vue";

export default {
  props: {
    bookInfo: Object,
  },
  components: {
    LogoComponent,
    TitleComponent,
    LabelComponent,
  },
};
</script>

// next/next-components/src/components/molecules/sidebar.jsx
import React from "react";
import LogoComponent from "../atoms/logo";
import TitleComponent from "../atoms/title";
import LabelComponent from "../atoms/label";

const SidebarComponent = ({ bookInfo }) => {
  const { title, subtitle, authors, description, year, pages, download } =
    bookInfo || {};

  return (
    <div className="sidebar">
      <LogoComponent selected={!!bookInfo}/>
      <TitleComponent text="Book Shelf" size="large" color="white"/>
      {bookInfo ? (
        <div
          style={{
            width: "15rem",
            height: "13rem",
            textAlign: "left",
            display: "flex",
            flexDirection: "column",
            gap: "1rem",
            overflowY: "scroll",
          }}
        >
          <div className="bookDescription">
            <LabelComponent text="Title:" size="medium" color="white" bold/>
            <LabelComponent text={title} size="medium" color="white" />
          </div>
          <div className="bookDescription">
            <LabelComponent text="Subtitle:" size="medium" color="white" bold/>
            <LabelComponent text={subtitle} size="medium" color="white"/>
          </div>
          <div className="bookDescription">
            <LabelComponent text="Authors:" size="medium" color="white" bold/>
            <LabelComponent text={authors} size="medium" color="white"/>
          </div>
          <div className="bookDescription">
            <LabelComponent text="Description:" size="medium" color="white" bold/>
            <LabelComponent text={description} size="medium" color="white"/>
          </div>
          <div className="bookDescription">
            <LabelComponent text="Year:" size="medium" color="white" bold/>
            <LabelComponent text={year} size="medium" color="white"/>
          </div>
          <div>
            <LabelComponent text="Pages:" size="medium" color="white" bold/>
            <LabelComponent text={pages} size="medium" color="white"/>
          </div>
          <a className="button" href={download} target="_blank">
            Download
          </a>
        </div>
      ) : (
        <>
          <LabelComponent
            text="(Select a book to see its specifications here!)"
            size="small"
            color="white"
          />
        </>
      )}
    </div>
  );
};

export default SidebarComponent;
