// vue/vue-components/src/components/molecules/BookItem.vue
<template>
  <div class="bookItem" @click="handleClick">
    <img :src="imagePath" style="width: 119px;height: 160px;" />
    <div class="bookItemTextContainer">
      <TitleComponent
        :text="title || 'Default Title'"
        size="small"
        :bold="true"
        :ellipsed="true"
      />
      <LabelComponent
        :text="label || 'Default Label'"
        size="small"
        :bold="true"
        :ellipsed="true"
        :color="'#7E7E7E'"
      />
    </div>
  </div>
</template>

<script>
import TitleComponent from '../atoms/title.vue';
import LabelComponent from '../atoms/Label.vue';
export default {
  props: {
    title: String,
    label: String,
    path: String,
    onClick: Function,
  },
  computed: {
    imagePath() {
      return this.path || "https://www.dbooks.org/img/books/5635349929s.jpg";
    },
  },
  methods: {
    handleClick() {
      if (this.onClick) {
        this.onClick();
      }
    },
  },
  components:{
    TitleComponent,
    LabelComponent
  }
};
</script>

// svelte/svelte-components/src/components/molecules/BookItemComponent.svelte
<script>
  import TitleComponent from "../atoms/TitleComponent.svelte";
  import LabelComponent from "../atoms/LabelComponent.svelte";

  export let title = "Default Title";
  export let label = "Default Label";
  export let path = "https://www.dbooks.org/img/books/5635349929s.jpg";
  export let onClick = () => {};

  function handleClick() {
    if (onClick) {
      onClick();
    }
  }
</script>

<div class="bookItem" on:click={handleClick}>
  <img src={path} alt="Book cover" width="119px" height="160px" />
  <div class="bookItemTextContainer">
    <TitleComponent text={title} size="small" bold ellipsed />
    <LabelComponent text={label} size="small" bold ellipsed color="#7E7E7E" />
  </div>
</div>
