// next/next-components/src/components/molecules/searchInput.jsx
import React, { useRef, useState } from "react";

const SearchInputComponent = ({ value, onChange }) => {
  const inputRef = useRef(null);
  const [inputValue, setInputValue] = useState(value || "");

  const handleInput = (event) => {
    const newValue = event.target.value;
    setInputValue(newValue);

    // Call the onChange function if it's provided
    if (onChange) {
      onChange(newValue);
    }
  };

  return (
    <div className="searchInputContainer">
      <img src="/icons/search.svg" alt="Search icon" width="18px" height="17px" style={{ marginLeft: ".5rem" }} />
      <input
        type="text"
        className="searchInput"
        placeholder="Search a book by its name or author"
        ref={inputRef}
        value={inputValue}
        onChange={handleInput}
      />
    </div>
  );
};

export default SearchInputComponent;

// svelte/svelte-components/src/components/molecules/SearchInputComponent.svelte
<script>
  // @ts-nocheck

  import { onMount } from "svelte";

  export let value = "";
  export let onChange = null;
  export let inputValue = value;

  const inputRef = undefined;

  const handleInput = (event) => {
    const newValue = event.target.value;
    inputValue = newValue;

    if (onChange) {
      onChange(newValue);
    }
  };

  onMount(() => {
    if (inputRef) {
      inputRef.value = value;
    }
  });
</script>

<div class="searchInputContainer">
  <img
    src="/icons/search.svg"
    alt="Search icon"
    width="18px"
    height="17px"
    style="margin-left: .5rem"
  />
  <input
    type="text"
    class="searchInput"
    placeholder="Search a book by its name or author"
    bind:value={inputValue}
    on:input={handleInput}
  />
</div>
