// angular/angular-components/src/components/molecules/search-input.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  AfterViewInit,
} from '@angular/core';

@Component({
  selector: 'search-input-component',
  template: `
    <div class="searchInputContainer">
      <img
        src="../assets/icons/search.svg"
        alt="Search icon"
        style="margin-left: 0.5rem; width: 18px; height: 17px;"
      />
      <input
        type="text"
        class="searchInput"
        placeholder="Search a book by its name or author"
        #inputRef
        [value]="inputValue"
        (input)="handleInput('')"
      />
    </div>
  `,
})
export class SearchInputComponent implements AfterViewInit {
  @Input() value: string = "";
  @Output() onChange: EventEmitter<string> = new EventEmitter<string>();

  inputValue: string = '';

  constructor(private el: ElementRef) {}

  ngAfterViewInit() {
    // Set the initial value of inputValue when the component is initialized
    this.inputValue = this.value || '';
  }

  handleInput(value: string) {
    this.inputValue = value;

    // Emit the value when the input changes
    this.onChange.emit(value);
  }
}

// svelte/svelte-components/src/components/molecules/SearchInputComponent.svelte
<script>
  // @ts-nocheck

  import { onMount } from "svelte";

  export let value = "";
  export let onChange = null;
  export let inputValue = value;

  const inputRef = undefined;

  const handleInput = (event) => {
    const newValue = event.target.value;
    inputValue = newValue;

    if (onChange) {
      onChange(newValue);
    }
  };

  onMount(() => {
    if (inputRef) {
      inputRef.value = value;
    }
  });
</script>

<div class="searchInputContainer">
  <img
    src="/icons/search.svg"
    alt="Search icon"
    width="18px"
    height="17px"
    style="margin-left: .5rem"
  />
  <input
    type="text"
    class="searchInput"
    placeholder="Search a book by its name or author"
    bind:value={inputValue}
    on:input={handleInput}
  />
</div>
