// vue/vue-components/src/components/atoms/Title.vue
<template>
  <div>
    <div
      :style="{
        fontWeight: bold ? 'bolder' : 'bold',
        fontFamily: 'Libre Baskerville, serif',
        fontSize: titleSizes[size] || titleSizes.medium,
        color: color || '#232323',
      }"
      :class="{ title: true, ellipsed: ellipsed }"
      :id="titleId"
    >
      {{ text }}
    </div>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      default: "Default Title",
    },
    size: {
      type: String,
      default: "medium",
    },
    color: {
      type: String,
      default: "",
    },
    bold: {
      type: Boolean,
      default: false,
    },
    ellipsed: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      titleSizes: {
        small: "0.75rem",
        medium: "1.25rem",
        large: "4rem",
      },
    };
  },
  computed: {
    titleId() {
      return "title";
    },
  },
};
</script>

<style scoped>
.title {
  font-family: "Libre Baskerville, serif";
}

.ellipsed {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>

// angular/angular-components/src/components/atoms/title.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'title-component',
  template: `
    <div>
      <div [ngStyle]="titleStyles" [ngClass]="titleClasses" [attr.id]="titleId">
        {{ text }}
      </div>
    </div>
  `,
  styles: [
    `
      .title {
        font-family: 'Libre Baskerville, serif';
      }
      .ellipsed {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
    `,
  ],
})
export class TitleComponent {
  @Input() text: string = 'Default Title';
  @Input() size: string = 'medium';
  @Input() color: string = '';
  @Input() bold: boolean = false;
  @Input() ellipsed: boolean = false;

  titleSizes = {
    small: '0.75rem',
    medium: '1.25rem',
    large: '4rem',
  };

  get titleStyles() {
    return {
      'font-weight': this.bold ? 'bolder' : 'bold',
      'font-family': 'Libre Baskerville, serif',
      'font-size': this.titleSizes[this.size as 'small' || 'medium' || 'large'] || this.titleSizes.medium,
      color: this.color || '#232323',
    };
  }

  get titleClasses() {
    return {
      title: true,
      ellipsed: this.ellipsed,
    };
  }

  get titleId() {
    return 'title';
  }
}
